### ISSUE TITLE
Brightness drops a little bit when refresh rate switches.

### ISSUE THREAD

**Issue by Vortex3008** [yc9559/dfps#11]
When the refresh rate switches to 60 hz the brightness of the display lowers just slightly but still noticeable and when it's at 120 brightness looks normal. This is most noticeable at lower brightness and on a black background.

**Comment by yc9559** [comment]
New feature added in [dynamic_fps: Disable if the screen brightness is low](https://github.com/yc9559/dfps/commit/89948e00952091097278dcae6af856b10a7938a7)
