### ISSUE TITLE
配置文件中2种刷新率切换方法中英文描述不符

### ISSUE THREAD

**Issue by woaiwinnie2** [yc9559/dfps#2]
方法1: PEAK_REFRESH_RATE法，值>=20
 Method 1: PEAK_REFRESH_RATE, value in [0, 20)

方法2: Surfaceflinger backdoor法，值<20
Method 2: Surfaceflinger backdoor, value in [20, +inf)

应为
方法1: PEAK_REFRESH_RATE法，值>=20
Method 1: PEAK_REFRESH_RATE, value in [20, +inf)

方法2: Surfaceflinger backdoor法，值<20
Method 2: Surfaceflinger backdoor, value in [0, 20)

**Comment by yc9559** [comment]
已确认，正式版会修复。
