### ISSUE TITLE
InputListener的CPU占用异常

### ISSUE THREAD

**Issue by chenzyyzd** [yc9559/dfps#6]
在没有触碰到屏幕的情况下InputListener的CPU占用偶尔会飙得很高，已经复现了四次，机型是一加ace极速版，系统是ColorOS12 Android12 ，dfps版本是22.08.21
![Screenshot_2022-09-03-10-14-20-16_507096bf411ffee187df405bf527ca60](https://user-images.githubusercontent.com/89340470/188252092-2a4876bd-ee34-45f3-9e25-d3af74bd9a69.jpg)
![Screenshot_2022-09-03-09-54-50-85_507096bf411ffee187df405bf527ca60](https://user-images.githubusercontent.com/89340470/188252097-74569abc-1477-4c38-bdf8-6251974d710b.jpg)

**Comment by chenzyadb** [comment]
I've already thrown that phone away.
