### ISSUE TITLE
Can anyone help me in editing this file through termux?

### ISSUE THREAD

**Issue by Shrtej** [yc9559/dfps#8]
I'm not good with commands on termux so idk how to run dfps.txt to change contents...I was able to just view the contents. Any help would be great!
Btw I'm using miui 12.5 , A11 based stock rom.

**Comment by Vortex3008** [comment]
Hello I have the same issue. I have no idea how to change anything or how to use the commands mentioned in the dfps.txt file. I guess with termux but I don't know how.

**Comment by Dianshii** [comment]
If you can't understand the config file just try this app https://www.coolapk.com/apk/com.sulisong.uperf (yc tool box)
It's a dfps and uperf manager. If you've installed dfps module, just open this app and you can change the default fps and per-app fps with English GUI in there. Btw if you're using a xiaomi device, you should turn on the "Enable Backdoor" botton to let it work.

**Comment by Vortex3008** [comment]
> If you can't understand the config file just try this app https://www.coolapk.com/apk/com.sulisong.uperf (yc tool box) It's a dfps and uperf manager. If you've installed dfps module, just open this app and you can change the default fps and per-app fps with English GUI in there. Btw if you're using a xiaomi device, you should turn on the "Enable Backdoor" botton to let it work.

thank you
